export const FETCH_DEFAULT = 'FETCH_DEFAULT';
export const FETCH_FROM_SEARCH = 'FETCH_FROM_SEARCH';
export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const CHANGE_SORTING = 'CHANGE_SORTING';
export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SELECT_MOVIE = 'SELECT_MOVIE';
